Enhance converters with allow serialize empty
saxulum/saxulum-elasticsearch-querybuilder pull request #3
Opened 2018-07-18 13:15 UTC by healerz

2018-07-18 13:32 UTC, dominikzogg commented
please replace 3.2 with 3.3:
https://github.com/saxulum/saxulum-elasticsearch-querybuilder/blob/master/composer.json#L24
https://github.com/saxulum/saxulum-elasticsearch-querybuilder/blob/master/README.md#installation

please add doc:
https://github.com/saxulum/saxulum-elasticsearch-querybuilder/blob/master/doc/Converter/IteratableToNodeConverter.md
https://github.com/saxulum/saxulum-elasticsearch-querybuilder/blob/master/doc/Converter/ScalarToNodeConverter.md

2018-07-18 13:33 UTC, dominikzogg requested changes
please replace 3.2 with 3.3:
https://github.com/saxulum/saxulum-elasticsearch-querybuilder/blob/master/composer.json#L24
https://github.com/saxulum/saxulum-elasticsearch-querybuilder/blob/master/README.md#installation

please add doc:
https://github.com/saxulum/saxulum-elasticsearch-querybuilder/blob/master/doc/Converter/IteratableToNodeConverter.md
https://github.com/saxulum/saxulum-elasticsearch-querybuilder/blob/master/doc/Converter/ScalarToNodeConverter.md

2018-07-18 15:10 UTC, healerz commented
@dominikzogg  ok like this? :)

2018-07-18 15:47 UTC, dominikzogg commented on doc/Converter/IteratableToNodeConverter.md
> +**Important**: By default empty nodes get not serialized. NullNode forces null value serialization.
I mean't another sample with the new argument

2018-07-20 08:37 UTC, dominikzogg approved these changes

2018-07-20 08:37 UTC, merged

2018-07-20 08:39 UTC, dominikzogg commented
@healerz thanks